import { Vector3 } from "@babylonjs/core";
import { instrument } from "./instruments";

export const instruments: Array<instrument> = [
  {
    id: 0,
    name: "Отвертка малая крестовая",
    imageSrc: "../assets/images/screwdriver.jpg",
    description:
      "Полезна для откручивания саморезов, болтов и прочего ковыряния",
    mesh: null,
    isActive: false,
    filename: "tool_turn_screw_01",
    position: new Vector3(-0.05, 0.1, -0.03),
    rotation: new Vector3(0, -Math.PI, Math.PI / 6.6),
  },
  {
    id: 1,
    name: "Отвертка средняя плоская",
    imageSrc: "../assets/images/screwdriver.jpg",
    description:
      "Полезна для откручивания саморезов, болтов и прочего ковыряния",
    mesh: null,
    isActive: false,
    filename: "tool_turn_screw_02",
    position: new Vector3(-0.035, 0.12, -0.03),
    rotation: new Vector3(0, -Math.PI, Math.PI / 6.6),
  },
  {
    id: 2,
    name: "Отвертка большая плоская",
    imageSrc: "../assets/images/screwdriver.jpg",
    description:
      "Полезна для откручивания саморезов, болтов и прочего ковыряния",
    mesh: null,
    isActive: false,
    filename: "tool_turn_screw_03",
    position: new Vector3(-0.05, 0.1, -0.03),
    rotation: new Vector3(0, -Math.PI, Math.PI / 6.6),
  },
  {
    id: 3,
    name: "Отвертка малая плоская",
    imageSrc: "../assets/images/screwdriver.jpg",
    description:
      "Полезна для откручивания саморезов, болтов и прочего ковыряния",
    mesh: null,
    isActive: false,
    filename: "tool_turn_screw_04",
    position: new Vector3(-0.035, 0.12, -0.03),
    rotation: new Vector3(0, -Math.PI, Math.PI / 6.6),
  },
  {
    id: 4,
    name: "Отвертка средняя крестовая",
    imageSrc: "../assets/images/screwdriver.jpg",
    description:
      "Полезна для откручивания саморезов, болтов и прочего ковыряния",
    mesh: null,
    isActive: false,
    filename: "tool_turn_screw_05",
    position: new Vector3(-0.06, 0.12, -0.03),
    rotation: new Vector3(0, -Math.PI, Math.PI / 6.6),
  },
  {
    id: 5,
    name: "Отвертка большая крестовая",
    imageSrc: "../assets/images/screwdriver.jpg",
    description:
      "Полезна для откручивания саморезов, болтов и прочего ковыряния",
    mesh: null,
    isActive: false,
    filename: "tool_turn_screw_06",
    position: new Vector3(-0.06, 0.12, -0.03),
    rotation: new Vector3(0, -Math.PI, Math.PI / 6.6),
  },
  {
    id: 6,
    name: "Детектор утечек",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_leak_detector",
    position: new Vector3(-0.075, 0.192, -0.027),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.7, Math.PI / 0.6),
  },
  {
    id: 7,
    name: "Насадка на рчажный труборасширитель2",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_lever_pipe_expander_nozzle_02",
    position: new Vector3(-0.058, 0.118, -0.027),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.7, Math.PI / 0.6),
  },
  {
    id: 8,
    name: "Насадка на рчажный труборасширитель3",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_lever_pipe_expander_nozzle_03",
    position: new Vector3(-0.058, 0.118, -0.027),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.7, Math.PI / 0.6),
  },
  {
    id: 9,
    name: "Насадка на рчажный труборасширитель4",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_lever_pipe_expander_nozzle_04",
    position: new Vector3(-0.058, 0.118, -0.027),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.7, Math.PI / 0.6),
  },
  {
    id: 10,
    name: "Насадка на рчажный труборасширитель5",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_lever_pipe_expander_nozzle_05",
    position: new Vector3(-0.058, 0.118, -0.027),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.7, Math.PI / 0.6),
  },
  {
    id: 11,
    name: "Насадка на рчажный труборасширитель6",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_lever_pipe_expander_nozzle_06",
    position: new Vector3(-0.058, 0.118, -0.027),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.7, Math.PI / 0.6),
  },
  {
    id: 12,
    name: "Насадка на рчажный труборасширитель7",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_lever_pipe_expander_nozzle_07",
    position: new Vector3(-0.058, 0.118, -0.027),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.7, Math.PI / 0.6),
  },
  {
    id: 13,
    name: "Насадка на рчажный труборасширитель1",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_lever_pipe_expander",
    position: new Vector3(-0.058, 0.118, -0.027),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.7, Math.PI / 0.6),
  },
  {
    id: 14,
    name: "Насадка на трубогиб арбалетного типа1",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_01",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 15,
    name: "Насадка на трубогиб арбалетного типа2",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_02",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 16,
    name: "Насадка на трубогиб арбалетного типа3",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_03",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 17,
    name: "Насадка на трубогиб арбалетного типа4",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_04",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 18,
    name: "ДНасадка на трубогиб арбалетного типа5",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_05",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 19,
    name: "Насадка на трубогиб арбалетного типа6",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_06",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 20,
    name: "Насадка на трубогиб арбалетного типа7",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_07",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 21,
    name: "Насадка на трубогиб арбалетного типа8",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_08",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 22,
    name: "Насадка на трубогиб арбалетного типа9",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow_nozzle_09",
    position: new Vector3(-0.046, 0.113, -0.027),
    rotation: new Vector3(Math.PI / 0.5, Math.PI / 0.7, Math.PI / 0.8),
  },
  {
    id: 23,
    name: "Трубогиб арбалетного типа",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_bender_crossbow",
    position: new Vector3(-0.096, 0.217, -0.026),
    rotation: new Vector3(0, 0, Math.PI / 0.55),
  },
  {
    id: 24,
    name: "Трубогиб пружинный 1.2мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_Pipe_bender_spring_1.2",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 0.54, 0, Math.PI / 0.53),
  },
  {
    id: 25,
    name: "Трубогиб пружинный 1.4мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_Pipe_bender_spring_1.4",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 0.54, 0, Math.PI / 0.53),
  },
  {
    id: 26,
    name: "Трубогиб пружинный 3.8мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_Pipe_bender_spring_3.8",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 0.54, 0, Math.PI / 0.53),
  },
  {
    id: 27,
    name: "Трубогиб пружинный 5.8мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_Pipe_bender_spring_5.8",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 0.54, 0, Math.PI / 0.53),
  },
  {
    id: 28,
    name: "Трубогиб пружинный 5.16мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_Pipe_bender_spring_5.16",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 0.54, 0, Math.PI / 0.53),
  },
  {
    id: 29,
    name: "Труборез большой",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_Pipe_cutter_big",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 0.54, 0, Math.PI / 0.53),
  },
  {
    id: 30,
    name: "Труборез малый",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_Pipe_cutter_small",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 4.8, Math.PI / 1.85, 0),
  },
  {
    id: 31,
    name: "Труборасширитель",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pipe_expander",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 0.53, Math.PI / 0.67, 0),
  },
  {
    id: 32,
    name: "Пласкогубцы",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_pliers",
    position: new Vector3(0, 0.147, -0.047),
    rotation: new Vector3(0, Math.PI / 0.69, Math.PI / 1.6),
  },
  {
    id: 33,
    name: "Риммер цилиндр",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_rimmer_barrel",
    position: new Vector3(-0.03, 0.107, -0.027),
    rotation: new Vector3(Math.PI / 1.487, Math.PI / 1.85, 0),
  },
  {
    id: 34,
    name: "Риммер карандаш",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_rimmer_pencil",
    position: new Vector3(-0.031, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.58, Math.PI / 0.66, 0),
  },
  {
    id: 35,
    name: "Вальцовка",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_rolling",
    position: new Vector3(-0.031, 0.1, -0.068),
    rotation: new Vector3(Math.PI / 0.54, 0, Math.PI / 1.06),
  },
  {
    id: 36,
    name: "Ножницы",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_scissors",
    position: new Vector3(-0.033, 0.098, -0.04),
    rotation: new Vector3(Math.PI / 0.6, Math.PI / 0.55, 0),
  },
  {
    id: 37,
    name: "Насадка на ключ ручку1",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_torque_wrench_nozzle_01",
    position: new Vector3(-0.041, 0.098, -0.04),
    rotation: new Vector3(Math.PI / 3.33, 0, 0),
  },
  {
    id: 38,
    name: "Насадка на ключ ручку2",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_torque_wrench_nozzle_02",
    position: new Vector3(-0.041, 0.098, -0.04),
    rotation: new Vector3(Math.PI / 3.33, 0, 0),
  },
  {
    id: 39,
    name: "Насадка на ключ ручку3",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_torque_wrench_nozzle_03",
    position: new Vector3(-0.041, 0.098, -0.04),
    rotation: new Vector3(Math.PI / 3.33, 0, 0),
  },
  {
    id: 40,
    name: "Насадка на ключ ручку4",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_torque_wrench_nozzle_04",
    position: new Vector3(-0.041, 0.098, -0.04),
    rotation: new Vector3(Math.PI / 3.33, 0, 0),
  },
  {
    id: 41,
    name: "Насадка на ключ ручку5",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_torque_wrench_nozzle_05",
    position: new Vector3(-0.041, 0.098, -0.04),
    rotation: new Vector3(Math.PI / 3.33, 0, 0),
  },
  {
    id: 42,
    name: "Насадка на ключ ручку6",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_torque_wrench_nozzle_06",
    position: new Vector3(-0.041, 0.098, -0.04),
    rotation: new Vector3(Math.PI / 3.33, 0, 0),
  },
  {
    id: 43,
    name: "Ключ ручка",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_torque_wrench.001",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 44,
    name: "Индикаторная отвертка",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_turn_screw_indicator",
    position: new Vector3(-0.036, 0.1, -0.03),
    rotation: new Vector3(0, 0, Math.PI / 3.53),
  },
  {
    id: 45,
    name: "Ключ 6мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_6mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 46,
    name: "Ключ 7мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_7mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 47,
    name: "Ключ 8мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_8mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 48,
    name: "Ключ 9мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_9mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 49,
    name: "Ключ 10мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_10mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 50,
    name: "Ключ 11мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_11mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 51,
    name: "Ключ 12мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_12mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 52,
    name: "Ключ 13мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_13mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 53,
    name: "Ключ 14мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_14mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 54,
    name: "Ключ 15мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_15mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 55,
    name: "Ключ 16мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_16mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 56,
    name: "Ключ 17мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_17mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 57,
    name: "Ключ 18мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_18mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 58,
    name: "Ключ 19мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_19mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 59,
    name: "Ключ 20мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_20mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 60,
    name: "Ключ 21мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_21mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 61,
    name: "Ключ 22мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_22mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 62,
    name: "Ключ 23мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_23mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 63,
    name: "Ключ 24мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_24mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 64,
    name: "Ключ 25мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_25mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 65,
    name: "Ключ 26мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_26mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 66,
    name: "Ключ 27мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_27mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 67,
    name: "Ключ 28мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_28mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 68,
    name: "Ключ 30мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_30mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 69,
    name: "Ключ 32мм",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_32mm",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  {
    id: 70,
    name: "Разводной ключ",
    imageSrc: "",
    description: "",
    mesh: null,
    isActive: false,
    filename: "tool_wrench_razvodnoi",
    position: new Vector3(-0.06, 0.1, -0.03),
    rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  },
  // {
  //   id: 71,
  //   name: "Вакууматор фреона",
  //   imageSrc: "",
  //   description: "",
  //   mesh: null,
  //   isActive: false,
  //   filename: "Tool_Freon_evacuator",
  //   position: new Vector3(-0.06, 0.1, -0.03),
  //   rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  // },
  // {
  //   id: 72,
  //   name: "Измерительный коллектор",
  //   imageSrc: "",
  //   description: "",
  //   mesh: null,
  //   isActive: false,
  //   filename: "Tool_Gauge_manifold",
  //   position: new Vector3(-0.06, 0.1, -0.03),
  //   rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  // },
  // {
  //   id: 73,
  //   name: "Вакуумный насос",
  //   imageSrc: "",
  //   description: "",
  //   mesh: null,
  //   isActive: false,
  //   filename: "Tool_Vacuum_pump",
  //   position: new Vector3(-0.06, 0.1, -0.03),
  //   rotation: new Vector3(Math.PI / 0.537, Math.PI / 0.66, 0),
  // },
];
